import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/pylaptop.png"
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import AnimatedText from '@/components/AnimatedText'
import { TypeAnimation } from 'react-type-animation';
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import TransitionEffect from '@/components/TransitionEffect'
import { motion } from "framer-motion";
import { fadeIn } from '@/components/variants'
export default function Home() {
  return (
    <>
      <Head>
        <title>Abhinav | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image src={profilePic} alt="Portfolio" className='w-full h-auto lg:hidden md:inline-block md:w-full' priority sizes='(max-width:768px)100vw,(max-width:1200px)50vw,50vw' />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText text="ABHINAV KUMAR" className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl ' />
              <motion.div variants={fadeIn('up', 0.4)} initial="hidden" whileInView={'show'} viewport={{ once: false, amount: 0.7 }}
                className='text-3xl font-secondary font-semibold md:text-2xl uppercase leading-[1] inline-block w-full h-auto'>
                <span className='text-dark dark:text-light mr-4'>I am a</span>
                <TypeAnimation sequence={[
                  'Full Stack Developer', 2000,
                  'Quality Analyst', 2000,
                  'ECE Engineer', 2000,
                  'Data Analyst', 2000,
                  'Software Developer', 2000,
                ]}
                  speed={50}
                  className=' text-primary dark:text-primaryDark '
                  wrapper='span'
                  repeat={Infinity}
                />
              </motion.div>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>Versatile full stack developer and quality analyst, bridging hardware and software. Specializing in web development, data analysis and software development, I craft innovative solutions and analysis using React, NextJs, TailwindCSS, and Python. Visit my portfolio to explore projects and bring your ideas to life!</p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link href='/AbhinavResume(April).pdf' target={'_blank'} className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base' download={true}>Resume <LinkArrow className={"w-6 ml-1"} /> </Link>
                <Link className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base' href='mailto:abhinavkumarpal890@gmail.com' target={'_blank'}>Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        {/* <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt='portfolio' className='w-full h-auto' />
        </div> */}
      </main>
    </>
  )
}
